# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c87d39cb684fc84eecb931d42bce33d0fa3235d44b976ca0a4cb7431b7b62daeedaaaaae661c5dbe966837d42bf8786f3f0376067d796b89a8a8bcb7ff937d3

test:
  secret_key_base: e8180cc56892e2a1a5cc528b88873a13052bf922c68ef7ec7284e46cdc67545719898b068f7d0357ec93b1f4d746d50b801157469063c5a081b05f98e57ec8d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
